version: "3"

services:
  mongo:
    container_name: mongo_office
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27018}:27017
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  chatgpt_telegram_bot:
    container_name: meowgpt_office
    image: maindian/meowgpt:office
    command: python3 bot/bot.py
    restart: always
 #   build:
 #     context: "."
 #     dockerfile: Dockerfile
    depends_on:
      - mongo

 # mongo_express:
 #   container_name: mongo-express_office
 #   image: mongo-express:latest
 #   restart: always
 #   ports:
 #    - 127.0.0.1:${MONGO_EXPRESS_PORT:-8082}:${MONGO_EXPRESS_PORT:-8082}
 #  environment:
 #    - ME_CONFIG_MONGODB_SERVER=mongo_office
 #    - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27018}
 #    - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
 #   - ME_CONFIG_MONGODB_AUTH_DATABASE=gpt_office
 #   - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
 #   - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
 #   - ME_CONFIG_MONGODB_URL=mongodb://mongo:27018
 # depends_on:
 #    - mongo
